// <auto-generated />
using System;
using Fieldore.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Fieldore.Infrastructure.Migrations
{
    [DbContext(typeof(FieldoreDbContext))]
    [Migration("20260320194122_AddBusinessAuthUserRelation")]
    partial class AddBusinessAuthUserRelation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Fieldore.Domain.Entities.AppUserProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auth_user_id");

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("TimeZone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("time_zone");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("user_profiles", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.AuthUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_hash");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password_salt");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("auth_users", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Business", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("auth_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("logo_url");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("TradeType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("trade_type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<string>("WebsiteUrl")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("website_url");

                    b.HasKey("Id");

                    b.HasIndex("AuthUserId")
                        .IsUnique();

                    b.ToTable("businesses", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.BusinessMembership", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("business_memberships", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.BusinessSubscription", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BillingCycle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("billing_cycle");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("PlanName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("plan_name");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider");

                    b.Property<string>("ProviderSubscriptionId")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("provider_subscription_id");

                    b.Property<DateOnly?>("RenewsOn")
                        .HasColumnType("date")
                        .HasColumnName("renews_on");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateOnly?>("TrialEndsOn")
                        .HasColumnType("date")
                        .HasColumnName("trial_ends_on");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId")
                        .IsUnique();

                    b.ToTable("business_subscriptions", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AlternatePhone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("alternate_phone");

                    b.Property<bool>("BillingSameAsService")
                        .HasColumnType("bit")
                        .HasColumnName("billing_same_as_service");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<string>("CompanyName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("company_name");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("GateCode")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("gate_code");

                    b.Property<string>("InternalNotes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("internal_notes");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("MobilePhone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("mobile_phone");

                    b.Property<string>("PetsNote")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pets_note");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("customers", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.CustomerAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<bool>("IsBilling")
                        .HasColumnType("bit")
                        .HasColumnName("is_billing");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_addresses", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.CustomerNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("CustomerId");

                    b.ToTable("customer_notes", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Estimate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmailSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_email_snapshot");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_name_snapshot");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<string>("EstimateNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("estimate_number");

                    b.Property<DateOnly?>("ExpiresOn")
                        .HasColumnType("date")
                        .HasColumnName("expires_on");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "EstimateNumber")
                        .IsUnique();

                    b.ToTable("estimates", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.EstimateLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("EstimateId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("estimate_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("service_name");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_price");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("EstimateId");

                    b.ToTable("estimate_line_items", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("BalanceDueAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("balance_due_amount");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("CustomerEmailSnapshot")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_email_snapshot");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("CustomerNameSnapshot")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("customer_name_snapshot");

                    b.Property<decimal>("DiscountAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("discount_amount");

                    b.Property<DateOnly>("DueOn")
                        .HasColumnType("date")
                        .HasColumnName("due_on");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("invoice_number");

                    b.Property<DateOnly>("IssuedOn")
                        .HasColumnType("date")
                        .HasColumnName("issued_on");

                    b.Property<Guid?>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<string>("NetTerms")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("net_terms");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("PurchaseOrderNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("purchase_order_number");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<decimal>("SubtotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("subtotal_amount");

                    b.Property<decimal>("TaxAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_amount");

                    b.Property<decimal>("TaxRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("tax_rate");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("total_amount");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "InvoiceNumber")
                        .IsUnique();

                    b.ToTable("invoices", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invoice_id");

                    b.Property<decimal>("LineTotal")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("line_total");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("quantity");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<decimal>("UnitRate")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("unit_rate");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("invoice_line_items", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Job", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("ActualEndAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_end_at");

                    b.Property<DateTimeOffset?>("ActualStartAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("actual_start_at");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<int?>("EstimatedDurationMinutes")
                        .HasColumnType("int")
                        .HasColumnName("estimated_duration_minutes");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("job_number");

                    b.Property<string>("JobType")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("job_type");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("priority");

                    b.Property<DateTimeOffset?>("ScheduledEndAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("scheduled_end_at");

                    b.Property<DateTimeOffset>("ScheduledStartAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("scheduled_start_at");

                    b.Property<Guid?>("SourceLeadId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("source_lead_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<bool>("UseCustomerPrimaryAddress")
                        .HasColumnType("bit")
                        .HasColumnName("use_customer_primary_address");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId", "JobNumber")
                        .IsUnique();

                    b.ToTable("jobs", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("bit")
                        .HasColumnName("is_primary");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId", "UserProfileId")
                        .IsUnique();

                    b.ToTable("job_assignments", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobChecklistItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("completed_at");

                    b.Property<Guid?>("CompletedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("completed_by_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit")
                        .HasColumnName("is_completed");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int")
                        .HasColumnName("sort_order");

                    b.Property<string>("TaskName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("task_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_checklist_items", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobNote", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("created_by_user_id");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_notes", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobPhoto", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Caption")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("caption");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("JobId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("job_id");

                    b.Property<string>("StoragePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("storage_path");

                    b.Property<DateTimeOffset?>("TakenAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("taken_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid?>("UploadedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("uploaded_by_user_id");

                    b.HasKey("Id");

                    b.HasIndex("JobId");

                    b.ToTable("job_photos", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Lead", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<DateTimeOffset?>("ContactedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("contacted_at");

                    b.Property<DateTimeOffset?>("ConvertedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("converted_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("customer_id");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("first_name");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("last_name");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("phone");

                    b.Property<string>("RequestedService")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("requested_service");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.ToTable("leads", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.PaymentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("invoice_id");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("method");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("PaidAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("paid_at");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("recorded_by_user_id");

                    b.Property<string>("ReferenceNumber")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("reference_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId");

                    b.ToTable("payment_records", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BusinessId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("business_id");

                    b.Property<string>("Category")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<decimal?>("DefaultUnitPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("default_unit_price");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("BusinessId");

                    b.ToTable("service_catalog_items", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.UserNotificationPreference", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("created_at");

                    b.Property<bool>("EmailEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("email_enabled");

                    b.Property<bool>("MarketingEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("marketing_enabled");

                    b.Property<bool>("PushEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("push_enabled");

                    b.Property<bool>("SmsEnabled")
                        .HasColumnType("bit")
                        .HasColumnName("sms_enabled");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("datetimeoffset")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserProfileId")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("user_profile_id");

                    b.HasKey("Id");

                    b.HasIndex("UserProfileId")
                        .IsUnique();

                    b.ToTable("user_notification_preferences", (string)null);
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.AppUserProfile", b =>
                {
                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("AppUserProfileId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("state_or_province");

                            b1.HasKey("AppUserProfileId");

                            b1.ToTable("user_profiles");

                            b1.WithOwner()
                                .HasForeignKey("AppUserProfileId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Business", b =>
                {
                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("BusinessId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("state_or_province");

                            b1.HasKey("BusinessId");

                            b1.ToTable("businesses");

                            b1.WithOwner()
                                .HasForeignKey("BusinessId");
                        });

                    b.Navigation("Address");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.BusinessMembership", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Business", null)
                        .WithMany("Memberships")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.CustomerAddress", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Customer", null)
                        .WithMany("Addresses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "Address", b1 =>
                        {
                            b1.Property<Guid>("CustomerAddressId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("state_or_province");

                            b1.HasKey("CustomerAddressId");

                            b1.ToTable("customer_addresses");

                            b1.WithOwner()
                                .HasForeignKey("CustomerAddressId");
                        });

                    b.Navigation("Address")
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.CustomerNote", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Customer", null)
                        .WithMany("Notes")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Estimate", b =>
                {
                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "BillingAddressSnapshot", b1 =>
                        {
                            b1.Property<Guid>("EstimateId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("billing_latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("billing_longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_state_or_province");

                            b1.HasKey("EstimateId");

                            b1.ToTable("estimates");

                            b1.WithOwner()
                                .HasForeignKey("EstimateId");
                        });

                    b.Navigation("BillingAddressSnapshot");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.EstimateLineItem", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Estimate", null)
                        .WithMany("LineItems")
                        .HasForeignKey("EstimateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Invoice", b =>
                {
                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "BillingAddressSnapshot", b1 =>
                        {
                            b1.Property<Guid>("InvoiceId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("billing_latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("billing_longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("billing_state_or_province");

                            b1.HasKey("InvoiceId");

                            b1.ToTable("invoices");

                            b1.WithOwner()
                                .HasForeignKey("InvoiceId");
                        });

                    b.Navigation("BillingAddressSnapshot");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.InvoiceLineItem", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Invoice", null)
                        .WithMany("LineItems")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Job", b =>
                {
                    b.OwnsOne("Fieldore.Domain.ValueObjects.Address", "ServiceAddress", b1 =>
                        {
                            b1.Property<Guid>("JobId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("city");

                            b1.Property<string>("Country")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("country");

                            b1.Property<decimal?>("Latitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("latitude");

                            b1.Property<string>("Line1")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line1");

                            b1.Property<string>("Line2")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("line2");

                            b1.Property<decimal?>("Longitude")
                                .HasColumnType("decimal(18,2)")
                                .HasColumnName("longitude");

                            b1.Property<string>("PostalCode")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("postal_code");

                            b1.Property<string>("StateOrProvince")
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("state_or_province");

                            b1.HasKey("JobId");

                            b1.ToTable("jobs");

                            b1.WithOwner()
                                .HasForeignKey("JobId");
                        });

                    b.Navigation("ServiceAddress");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobAssignment", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Job", null)
                        .WithMany("Assignments")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobChecklistItem", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Job", null)
                        .WithMany("ChecklistItems")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobNote", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Job", null)
                        .WithMany("Notes")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.JobPhoto", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Job", null)
                        .WithMany("Photos")
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.PaymentRecord", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Invoice", null)
                        .WithMany("Payments")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.ServiceCatalogItem", b =>
                {
                    b.HasOne("Fieldore.Domain.Entities.Business", null)
                        .WithMany("Services")
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Business", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Services");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Customer", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Notes");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Estimate", b =>
                {
                    b.Navigation("LineItems");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Invoice", b =>
                {
                    b.Navigation("LineItems");

                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Fieldore.Domain.Entities.Job", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("ChecklistItems");

                    b.Navigation("Notes");

                    b.Navigation("Photos");
                });
#pragma warning restore 612, 618
        }
    }
}
